debug: False
###########
# Dataset #
###########
data_root: './data'
data_name: 'imdb_wiki'
data_version: 'clean1000'
batch_size: 256
num_workers: 8
eval_batch_size: 256
eval_num_workers: 4
batch_iter: 1

noise:
  type: 'symmetric'
  corrupt_p: 0.20 # 0.20, 0.40, 0.60
  std: 23
  std_min: 10
  std_max: 50

label_split: [4]

imbalance: False
oversample: False

x_c: 3
x_h: 128
x_w: 128

#########
# Model #
#########
device: 'cuda'
model_name: 'crust'
net: 'resnet50'

classification: True

mixup:
  active: False
  alpha: 1

# save pred_clean_idcs interval
save_every: 1

r: 1 # [1,2,4]
fl_ratio: 0.5 # [0.3, 0.5, 0.7, 0.9]
warmup: 5

cmixup:
  active: False
  batch_cmixup: False
  manifold_mixup: False
  kde_bandwidth: 1.5
  beta_alpha: 1

#########
# Train #
#########
total_epochs: 120

loss: 'ce' # l1 | mse

optimizer:
  type: Adam
  options:
    lr: 0.001

lr_scheduler:
  type: CosineAnnealingLR
  options:
    eta_min: 0
    last_epoch: -1

optimizer_ft:
  type: Adam
  options:
    lr: 0.002

lr_scheduler_ft:
  type: StepLR
  options:
    step_size: 300
    gamma: 0.1

# clip_grad:
  # type: value
  # options:
#    clip_value: 0.5

##########################
# discrete Exp. training #
##########################
train_expert: True # train expert and extract feature sequentially
filter_load: ''
refurb_load: ''

######################
# regressor training #
######################
selective_train_regress: True
regress_refurbish: false
regress_batch_size: 256
regress_total_epochs: 120
regress_model: 'vanilla'
regress_net: 'resnet50_regress'
regress_loss: 'mse' # l1 | mse | sce | ce | mixed(for headpose)
regress_warm_up: 5

regress_optimizer:
  type: Adam
  options:
    lr: 0.001

regress_lr_scheduler:
  type: CosineAnnealingLR
  options:
    eta_min: 0
    last_epoch: -1

regress_optimizer_ft:
  type: Adam
  options:
    lr: 0.002

regress_lr_scheduler_ft:
  type: StepLR
  options:
    step_size: 300
    gamma: 0.1

online_filtering: True
offline_filtering: False
offline_filtering_epoch: 120

########
# Eval #
########
eval: True
eval_every: 1

tensorboard:
  grad: False

########
# Etc #
########
task_lr_reset: False
save_weights: False
tqdm: False
overwrite_log: True
use_recent_identifier: False
